onboarding = false

[theme]
name = "catppuccin"

[theme.custom]
accent = "#89b4fa"

[terminal]
shell_mode = "auto"
new_cwd = "follow"

[keys]
prefix = "ctrl+g"
help = "prefix+?"
settings = "prefix+s"
detach = "prefix+q"
reload_config = "prefix+shift+r"
workspace_picker = "prefix+w"
goto = "prefix+g"
new_workspace = "prefix+shift+n"
rename_workspace = "prefix+shift+w"
close_workspace = "prefix+shift+d"
new_tab = "prefix+t"
rename_tab = "prefix+shift+t"
previous_tab = "prefix+p"
next_tab = "prefix+n"
switch_tab = "prefix+1..9"
close_tab = "prefix+shift+x"
rename_pane = "prefix+c"
edit_scrollback = "prefix+e"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
cycle_pane_next = "prefix+tab"
cycle_pane_previous = "prefix+shift+tab"
split_vertical = "prefix+v"
split_horizontal = "prefix+d"
close_pane = "prefix+x"
zoom = "prefix+z"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"
switch_workspace = "prefix+shift+1..9"
focus_agent = "prefix+alt+1..9"
last_pane = "prefix+backtick"
open_worktree = "prefix+shift+o"

[worktrees]
directory = "~/Projects/herdr-worktrees"

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = false
copy_on_select = true
pane_borders = true
pane_gaps = true
accent = "#89b4fa"
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = true
hide_tab_bar_when_single_tab = true

[ui.toast]
delivery = "terminal"
delay_seconds = 2

[ui.sidebar.agents]
rows = [
  ["state_icon", "agent", "state_text"],
  ["terminal_title_stripped"],
  ["workspace", "tab"],
]

[[keys.command]]
key = "alt+h"
type = "shell"
command = "herdr pane focus --current --direction left"
description = "Focus pane left"

[[keys.command]]
key = "alt+j"
type = "shell"
command = "herdr pane focus --current --direction down"
description = "Focus pane down"

[[keys.command]]
key = "alt+k"
type = "shell"
command = "herdr pane focus --current --direction up"
description = "Focus pane up"

[[keys.command]]
key = "alt+l"
type = "shell"
command = "herdr pane focus --current --direction right"
description = "Focus pane right"

[[keys.command]]
key = "alt+r"
type = "shell"
command = "herdr pane split --current --direction right --focus"
description = "Split pane right"

[[keys.command]]
key = "alt+d"
type = "shell"
command = "herdr pane split --current --direction down --focus"
description = "Split pane down"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "85%"
